-- MySQL Script generated by MySQL Workbench
-- 04/19/17 19:13:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS [quiz] DEFAULT CHARACTER SET utf8 ;
USE [quiz] ;

-- -----------------------------------------------------
-- Table [quiz].[Pytania]
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS [quiz].[Pytania] (
  [idPytania] INT NOT NULL AUTO_INCREMENT,
  [Pytania] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idPytania]),
  UNIQUE INDEX [Pytania_UNIQUE] ([Pytania] ASC),
  UNIQUE INDEX [idPytania_UNIQUE] ([idPytania] ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table [quiz].[DobreOdpowiedzi]
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS [quiz].[DobreOdpowiedzi] (
  [idDobreOdpowiedzi] INT NOT NULL AUTO_INCREMENT,
  [DobreOdpowiedzi] VARCHAR(45) NOT NULL,
  [Pytania_idPytania] INT NOT NULL,
  PRIMARY KEY ([idDobreOdpowiedzi], [Pytania_idPytania]),
  UNIQUE INDEX [DobreOdpowiedzi_UNIQUE] ([DobreOdpowiedzi] ASC),
  UNIQUE INDEX [idDobreOdpowiedzi_UNIQUE] ([idDobreOdpowiedzi] ASC),
  INDEX [fk_DobreOdpowiedzi_Pytania1_idx] ([Pytania_idPytania] ASC),
  CONSTRAINT [fk_DobreOdpowiedzi_Pytania1]
    FOREIGN KEY ([Pytania_idPytania])
    REFERENCES [quiz].[Pytania] ([idPytania])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table [quiz].[ZleOdpowiedzi]
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS [quiz].[ZleOdpowiedzi] (
  [idZleOdpowiedzi] INT NOT NULL AUTO_INCREMENT,
  [ZleOdpowiedzi] VARCHAR(45) NOT NULL,
  [Pytania_idPytania] INT NOT NULL,
  PRIMARY KEY ([idZleOdpowiedzi], [Pytania_idPytania]),
  INDEX [fk_Z³eOdpowiedzi_Pytania1_idx] ([Pytania_idPytania] ASC),
  UNIQUE INDEX [idZleOdpowiedzi_UNIQUE] ([idZleOdpowiedzi] ASC),
  CONSTRAINT [fk_Z³eOdpowiedzi_Pytania1]
    FOREIGN KEY ([Pytania_idPytania])
    REFERENCES [quiz].[Pytania] ([idPytania])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table [quiz].[TabelaWynikow]
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS [quiz.][TabelaWynikow] (
  [idTabelaWynikow] INT NOT NULL AUTO_INCREMENT,
  [Wynik] INT NOT NULL,
  [ilDobrychOdp] INT NOT NULL,
  [Nick] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idTabelaWynikow]),
  UNIQUE INDEX [idTabelaWynikow_UNIQUE] ([idTabelaWynikow] ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
