//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quizEntities : DbContext
    {
        public quizEntities()
            : base("name=quizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DobreOdpowiedzi> DobreOdpowiedzi { get; set; }
        public virtual DbSet<Pytania> Pytania { get; set; }
        public virtual DbSet<ZleOdpowiedzi> ZleOdpowiedzi { get; set; }
    }
}
