//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pytania()
        {
            this.DobreOdpowiedzi = new HashSet<DobreOdpowiedzi>();
            this.ZleOdpowiedzi = new HashSet<ZleOdpowiedzi>();
        }
    
        public int idPytania { get; set; }
        public string Pytania1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DobreOdpowiedzi> DobreOdpowiedzi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZleOdpowiedzi> ZleOdpowiedzi { get; set; }
    }
}
