//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaWynikow
    {
        public int idTabelaWynikow { get; set; }
        public int Wynik { get; set; }
        public int ilDobrychOdp { get; set; }
        public string Nick { get; set; }
    }
}
